AJobBoard/Models/Data/Apply.cs
using System;

namespace AJobBoard.Models
{
    public class Apply
    {
        public Apply()
        {
            DateAddedToApplies = DateTime.UtcNow;
        }
        public int Id { get; set; }
        public JobPosting JobPosting { get; set; }
        public ApplicationUser Applier { get; set; }
        public DateTime DateAddedToApplies { get; set; }
    }
}

AJobBoard/Models/Entity/Apply.cs
using System;

namespace AJobBoard.Models.Entity
{
    public class Apply
    {
        public Apply()
        {
            DateAddedToApplies = DateTime.UtcNow;
        }
        public int Id { get; set; }
        public JobPosting JobPosting { get; set; }
        public int? JobPostingId { get; set; }
        public ApplicationUser Applier { get; set; }
        public string? ApplierId { get; set; }
        public DateTime DateAddedToApplies { get; set; }
    }
}

AJobBoard/Controllers/Views/AppliesController.cs
using AJobBoard.Data;
using AJobBoard.Models.Dto;
using AJobBoard.Models.Entity;
using AJobBoard.Models.View;
using Jobtransparency.Models.Dto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace AJobBoard.Controllers.Views
{
    [Authorize]
    public class AppliesController : Controller
    {
        private readonly IAppliesRepository _appliesRepository;

        private readonly IUserRepository _userRepository;

        public AppliesController(IAppliesRepository appliesRepository, IUserRepository userRepository)
        {
            _appliesRepository = appliesRepository;
            _userRepository = userRepository;
        }

        // GET: Applies
        public async Task<IActionResult> Index()
        {

            ApplicationUser currentUser = await _userRepository.getUserFromHttpContextAsync(HttpContext);

            System.Collections.Generic.List<AppliesDTO> applications = await _appliesRepository.GetUsersAppliesAsync(currentUser);

            AppliesIndexViewModel vm = new AppliesIndexViewModel();

            foreach (AppliesDTO applies in applications)
            {
                vm.Applies.Add(new AppliesIndexDTO
                {
                    Id = applies.Id,
                    JobId = applies.JobId,
                    Title = applies.Title,
                    Company = applies.Company,
                    Location = applies.Location,
                    JobSource = applies.JobSource,
                    Applicates = applies.Applicates,
                    Views = applies.Views,
                    URL = applies.URL,
                    PostDate = applies.PostDate
                });
            }

            return View(vm);
        }

        public async Task<IActionResult> Delete(int applyId)
        {
            await _appliesRepository.DeleteAppliesAsync(applyId);
            return RedirectToAction("Index");
        }
    }
}

AJobBoard/Views/Applies/Delete.cshtml
@model AJobBoard.Models.Entity.Apply

@{
    ViewData["Title"] = "Delete";
}
<section class="site-section" style="background-color: burlywood; padding-top: 200px; padding-right: 20px; padding-left: 20px;">
    <h2 style="text-align: center; color: white; padding-bottom: 20px">Are you sure you want to delete this?</h2>

    <div class="container">
        <h5>Are you sure you want to delete this application ?</h5>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DateAddedToApplies)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DateAddedToApplies)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.JobPosting.Title)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model =>  model.JobPosting.Title)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.JobPosting.Company)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model =>  model.JobPosting.Company)
            </dd>
        </dl>

        <form asp-action="Delete" asp-antiforgery="true">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
        <a asp-action="Index" class="btn btn-primary">Back to List</a>

    </div>
</section>

AJobBoard/Views/Applies/Index.cshtml
@model AJobBoard.Models.View.AppliesIndexViewModel

<section class="site-section" style="background-color: burlywood;padding-top:200px; padding-right: 20px; padding-left: 20px;">

    <h2 style="text-align: center; color: white; padding-bottom: 20px">My Applies</h2>

    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-12">
                @if (Model.Applies.Count > 0)
                {
                    <div class="grid ml-5">
                        @foreach (var item in Model.Applies)
                        {
                            <div class="grid-item">
                                <div class="card m-4" style="width: 18rem;">
                                    <div class="card-body">
                                        <h5 class="card-title">@item.Title</h5>
                                        <a class="btn btn-info" asp-controller="JobPostings" asp-action="Details" asp-route-id="@item.Id">View</a>
                                        <a class="btn btn-danger" asp-controller="Applies" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                    </div>
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item">Company: @item.Company</li>
                                        <li class="list-group-item">Location: @item.Location</li>
                                        <li class="list-group-item">JobSource: @item.JobSource</li>
                                        <li class="list-group-item">Views: @item.Views</li>
                                    </ul>
                                </div>
                            </div>
                        }
                    </div>
                }else
                {
                    <h5 class="text-center"> You don't have any applies yet</h5>
                }
            </div>

        </div>
    </div>

</section>


@section Scripts {
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
    <script>
        $(document).ready(function () {
            $('.grid').isotope({
                itemSelector: '.grid-item',
                layoutMode: 'fitRows'
            });
        });
    </script>
}