AJobBoard/Models/Data/JobPosting.cs
using AJobBoard.Models.Data;
using System;
using System.Collections.Generic;

namespace AJobBoard.Models
{
    public class JobPosting
    {
        public JobPosting()
        {
            DateAdded = DateTime.UtcNow;
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Company { get; set; }
        public string Location { get; set; }
        public string PostDate { get; set; }
        public string Salary { get; set; }
        public string Posters { get; set; }
        public string JobSource { get; set; }
        public int NumberOfApplies { get; set; }
        public int NumberOfViews { get; set; }
        public List<Apply> Applies { get; set; }
        public ApplicationUser Poster { get; set; }
        public DateTime DateAdded { get; set; }
        public List<KeyPhrase> KeyPhrases { get; set; }
        public string Summary { get; set; }
    }
}

AJobBoard/Models/Entity/JobPosting.cs
using Jobtransparency.Models.Entity;
using NpgsqlTypes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AJobBoard.Models.Entity
{
    public class JobPosting
    {
        public JobPosting()
        {
            DateAdded = DateTime.UtcNow;
            Tags = new List<Tag>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Company { get; set; }
        public string Location { get; set; }
        public string PostDate { get; set; }
        public string Salary { get; set; }
        public string Posters { get; set; }
        public string JobSource { get; set; }
        public int NumberOfApplies { get; set; }
        public int NumberOfViews { get; set; }
        public List<Apply> Applies { get; set; }
        public ApplicationUser Poster { get; set; }
        public string? PosterId { get; set; }
        public DateTime DateAdded { get; set; }
        public List<KeyPhrase> KeyPhrases { get; set; }
        public Sentiment Sentiment { get; set; }
        public string Summary { get; set; }
        public bool Expried { get; set; } = false;
        public List<Tag> Tags { get; set; }
        public List<JobPostingTag> JobPostingTags { get; set; }
        public string CompanyLogoUrl { get; set; }
        public string Slug { get; set; }
    }
}

AJobBoard/Controllers/Views/JobPostingsController.cs
using AJobBoard.Data;
using AJobBoard.Models.Dto;
using AJobBoard.Models.Entity;
using AJobBoard.Models.View;
using AJobBoard.Services;
using AJobBoard.Utils.ControllerHelpers;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace AJobBoard.Controllers.Views
{
    [AllowAnonymous]
    public class JobPostingsController : Controller
    {
        private readonly IJobPostingRepository _jobPostingRepository;
        private readonly INLTKService _nltkService;
        private readonly IKeyPharseRepository _keyPharseRepository;
        private readonly IMapper _mapper;

        public JobPostingsController(
            IMapper mapper,
            IJobPostingRepository jobPostingRepository,
            INLTKService nltkService,
            IKeyPharseRepository keyPharseRepository)
        {
            _jobPostingRepository = jobPostingRepository;
            _nltkService = nltkService;
            _keyPharseRepository = keyPharseRepository;
            _mapper = mapper;
        }


        [HttpGet]
        public async Task<IActionResult> Index(int? pageNumber, string? keywords)
        {

            HomeIndexViewModel homeIndexVm = JobPostingHelper.SetDefaultFindModel(new HomeIndexViewModel());

            homeIndexVm.FindModel.Page = pageNumber ?? 1;
            homeIndexVm.FindModel.KeyWords = keywords ?? "";

            JobPostingHelper.SetupViewBag(homeIndexVm, ViewBag);

            List<JobPostingDTO> result = await _jobPostingRepository.ConfigureSearch(homeIndexVm);

            string count = _jobPostingRepository.GetTotal();

            ViewBag.MaxPage = int.Parse(count) / homeIndexVm.FindModel.Page;

            ViewBag.Page = homeIndexVm.FindModel.Page;
            homeIndexVm.JobPostings = result;
            return View(homeIndexVm);
        }

        [HttpPost]
        public IActionResult IndexPost(HomeIndexViewModel homeIndexVm)
        {
            homeIndexVm = JobPostingHelper.SetDefaultFindModel(homeIndexVm);

            JobPostingHelper.SetupViewBag(homeIndexVm, ViewBag);

            return RedirectToAction("Index", new
            {
                pageNumber = homeIndexVm.FindModel.Page,
                keywords = homeIndexVm.FindModel.KeyWords
            });
        }


        // GET: JobPostings/Details/5
        public async Task<IActionResult> Details(int id)
        {
            JobPosting jobPosting = await _jobPostingRepository.GetById(id);
            if (jobPosting == null)
            {
                return NotFound();
            }

            jobPosting = await _jobPostingRepository.IncrementNumberOfViews(jobPosting);

            return View(new JobPostingDetailViewModel()
            {
                CurrentJobPosting = jobPosting,
            });
        }

    }
}

AJobBoard/Views/JobPostings/Details.cshtml
@model AJobBoard.Models.View.JobPostingDetailViewModel
@{ ViewData["SEO_Info_Title"] = Model.CurrentJobPosting.Title + " - " + Model.CurrentJobPosting.Company;
                ViewData["SEO_Info_Description"] = Model.CurrentJobPosting.Summary; }
<section class="section-hero overlay inner-page bg-image" style="background-image: url(@Model.ImageName);"
         id="home-section">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="headerdetail text-white font-weight-bold">@ViewData["SEO_Info_Title"]</h1>
            </div>
        </div>
    </div>
</section>

@Html.AntiForgeryToken()

<section class="site-section">
    <div class="container">
        <div class="row align-items-center mb-5">
            <div class="col-lg-8 mb-4 mb-lg-0">
                <div class="d-flex align-items-center">
                    <div>
                        <h2>@Html.DisplayFor(model => model.CurrentJobPosting.Title)</h2>
                        <div>
                            @if (!string.IsNullOrEmpty(Model.CurrentJobPosting.Company))
                            {
                <span class="ml-0 mr-2 mb-2"><span class="icon-briefcase mr-2"></span>@Html.DisplayFor(model => model.CurrentJobPosting.Company)</span> }
            else
            {
<span class="ml-0 mr-2 mb-2"><span class="icon-briefcase mr-2"></span>N/A</span>}
                            @if (!string.IsNullOrEmpty(Model.CurrentJobPosting.Location))
                            {
                <span class="m-2"><span class="icon-room mr-2"></span>@Html.DisplayFor(model => model.CurrentJobPosting.Location)</span> }
            else
            {
<span class="m-2"><span class="icon-room mr-2"></span>N/A</span>}

                            <span class="m-2">
                                <span class="icon-clock-o mr-2"></span><span class="text-primary">
                                    Full
                                    Time
                                </span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="row">
                    <div class="col-6">
                        <a href="#" data-id="@Model.CurrentJobPosting.Id" class="btn btn-block btn-light btn-md AddToApplies">
                            <span class="icon-heart-o mr-2 text-danger"></span>Add To Applies
                        </a>
                    </div>
                    <div class="col-6">
                        @if (Model.CurrentJobPosting.JobSource.Equals("Indeed"))
                        {
                    <a href="@Model.CurrentJobPosting.URL" target="_blank" class="btn btn-block btn-primary btn-md">View On Indeed</a> }
                                else
                                {
                    <a href="@Model.CurrentJobPosting.URL" target="_blank" class="btn btn-block btn-primary btn-md">View On Remote Ok</a>}
                    </div>
                    <div style="margin-top:20px;" class="col-6">
                        <a href="/JobPostings/" class="btn btn-block btn-warning btn-md">Back</a>
                    </div>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="mb-5">
                    <h3 class="h5 d-flex align-items-center mb-4 text-primary">
                        <span class="icon-align-left mr-3"></span>Job
                        Description
                    </h3>
                    <p>
                        @Html.Raw(System.Net.WebUtility.HtmlDecode(Model.CurrentJobPosting.Description).Replace(@"\", ""))
                    </p>
                </div>

            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script>
        $(document).ready(function () {
            var antiForgeryToken = $("input[name='__RequestVerificationToken']").val();
            $('.AddToApplies').click(function () {
                var d = $(this).data('id');
                $.ajax({
                    method: "POST",
                    contentType: 'application/json',
                    headers: { "RequestVerificationToken": antiForgeryToken },
                    url: "/api/AppliesAPI/addToUserApplies/" + parseInt(d),
                    success: function (data) {
                        alertify.success("Added to Applies");
                    },
                    error: function (xhr) {
                        alertify.error("Could Not Add this Job to your Applies");
                    }
                })
            });
        });
    </script>

}

AJobBoard/Views/JobPostings/Index.cshtml
@using System.Text.RegularExpressions
@model AJobBoard.Models.View.HomeIndexViewModel

<section class="site-section JobPostingList" style="background-color: #343a40;">
<div class="container">
<div class="row mb-5 justify-content-center jobpostingform">
    <div class="col-md-12 text-center">
        @using (Html.BeginForm("IndexPost", "JobPostings", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="row mb-5">
                <div class="col-12">
                    <h6 style="color:white">Key Words</h6>
                    <input style="height:47px;" type="text" name="FindModel.KeyWords"
                           class="form-control form-control-lg" placeholder="Job title, keywords..."
                           value="@(ViewBag.KeyWords ?? "")">
                </div>


                @if (ViewBag.Page == null)
                {
                    <input type="hidden" name="FindModel.Page" value="@(ViewBag.Page)"/>
                }
                else
                {
                    <input type="hidden" name="FindModel.Page" value="0"/>
                }

            </div>
            <div class="row mb-5">
                <div class="col-4"></div>
                <div class="col-4">
                    <button type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Job</button>
                </div>
                <div class="col-4"></div>

            </div>
        }
    </div>
</div>

<div class="mb-5">
@if (Model.JobPostings.Count() > 0)
{
    <div class="row">
        <div class="col-4">

        </div>
        <div class="col-4">
            <div class="row text-center">
                <div class="col-md-12 text-center text-md-left">
                    <div class="ml-auto">
                        <div class="row">
                            <div class="col-4">
                                @if (ViewBag.Page > 0 && ViewBag.Page != 1)
                                {
                                    @using (Html.BeginForm("IndexPost", "JobPostings", FormMethod.Post))
                                    {
                                        <input type="hidden" name="FindModel.KeyWords" value="@ViewBag.KeyWords"/>
                                        <input type="hidden" name="FindModel.Location" value="@ViewBag.Location"/>
                                        <input type="hidden" name="FindModel.MaxResults" value="@ViewBag.MaxResults"/>
                                        <input type="hidden" name="FindModel.Page" value="@(ViewBag.Page - 1)"/>
                                        <button type="submit" class="btn btn-primary btn-lg left top">&laquo; Prev</button>
                                    }
                                }
                            </div>

                            <div class="col-4">

                            </div>
                            <div class="col-4 ">
                                @if (ViewBag.Page < ViewBag.MaxPage)
                                {
                                    @using (Html.BeginForm("IndexPost", "JobPostings", FormMethod.Post))
                                    {
                                        <input type="hidden" name="FindModel.KeyWords" value="@ViewBag.KeyWords"/>
                                        <input type="hidden" name="FindModel.Location" value="@ViewBag.Location"/>
                                        <input type="hidden" name="FindModel.MaxResults" value="@ViewBag.MaxResults"/>
                                        <input type="hidden" name="FindModel.page" value="@(ViewBag.Page + 1)"/>
                                        <button type="submit" class="btn btn-primary btn-lg right top">Next &raquo;</button>
                                    }
                                }
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">

        </div>
    </div>

    <div class="border-top pb-3 mb-3 pt-3" style="margin-top: 20px;">
    </div>

    @foreach (var item in Model.JobPostings)
    {
        <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
            <div class="col-md-2">
                <button data-id="@item.Id" class="btn btn-warning AddToApplies">Add To Applies</button>
                <div class="spacer">
                </div>
                <button data-id="@item.Id" class="btn btn-warning ViewSummary">View Summary</button>
            </div>
            <div class="col-md-4 Summary_@item.Id" style="color:beige;display: none;">
                @if (!string.IsNullOrEmpty(item.Summary))
                {
                    <p style="color: black" class="meta">
                        @if (item.Summary.Length > 300)
                        {
                            @item.Summary.Substring(0, 300)
                        }
                        else
                        {
                            @item.Summary
                        }
                    </p>
                    <a asp-controller="JobPostings" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary float-right">Read More</a>
                }
                else
                {
                    <p>None Found</p>
                }
            </div>
            <div class="col-md-4" style="color: beige">
                @if (item.Title.ToLower().Contains("devops") || item.Title.ToLower().Contains("dev ops"))
                {
                    <span class="badge badge-primary px-2 py-1 mb-3">Dev Ops</span>
                }
                else
                {
                    if (item.Tags.Count > 0)
                    {
                        @foreach (var tag in item.Tags)
                        {
                            <span class="badge badge-primary px-2 py-1 mb-3">@tag.Text</span>
                        }
                    }
                    else
                    {
                        if (item.KeyPhrases.Count > 0)
                        {
                            foreach (var KeyPhrase in item.KeyPhrases)
                            {
                                
                                if (KeyPhrase.Affinty > 5 && KeyPhrase.Text.Length < 14)
                                {
                                    <span class="badge badge-primary px-2 py-1 mb-3">@KeyPhrase.Text</span>
                                }
                            }
                        }
                        else
                        {
                            <span class="badge badge-primary px-2 py-1 mb-3">Software</span>
                        }
                    }
                }
                <h2>
                    <a asp-controller="JobPostings" asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Title)</a>
                </h2>
                <p style="color: beige" class="meta">Publisher: <strong style="color: beige">@item.JobSource </strong></p>
            </div>

            <div class="col-md-2 text-left">
                <h3 style="color: beige">@Html.DisplayNameFor(model => model.FindModel.Location):</h3>
                @if (string.IsNullOrEmpty(item.Location))
                {
                    <h3 style="color: beige">Non - Found</h3>
                }
                else
                {
                    <h3 style="color: beige">@Html.DisplayFor(modelItem => item.Location)</h3>
                }
            </div>
            <div class="col-md-2" style="color: beige">
                <h5>Company :</h5>
                <strong style="color: beige">@Html.DisplayFor(modelItem => item.Company)</strong>

            </div>
            <div class="col-md-2 text-md-right" style="color: beige">
                <h5>Date Posted :</h5>
                <strong style="color: beige">@item.DateAdded.ToShortDateString()</strong>

            </div>
        </div>
    }


    <div class="row">
        <div class="col-4">

        </div>
        <div class="col-4">
            <div class="row text-center">
                <div class="col-md-12 text-center text-md-left">
                    <div class="ml-auto">
                        <div class="row">
                            <div class="col-4">
                                @if (ViewBag.Page > 0 && ViewBag.Page != 1)
                                {
                                    @using (Html.BeginForm("IndexPost", "JobPostings", FormMethod.Post))
                                    {
                                        <input type="hidden" name="FindModel.KeyWords" value="@ViewBag.KeyWords"/>
                                        <input type="hidden" name="FindModel.Location" value="@ViewBag.Location"/>
                                        <input type="hidden" name="FindModel.MaxResults" value="@ViewBag.MaxResults"/>
                                        <input type="hidden" name="FindModel.Page" value="@(ViewBag.Page - 1)"/>
                                        <button type="submit" class="btn btn-primary btn-lg left bottom">&laquo; Prev</button>
                                    }
                                }
                            </div>

                            <div class="col-4">

                            </div>
                            <div class="col-4 ">
                                @if (ViewBag.Page < ViewBag.MaxPage)
                                {
                                    @using (Html.BeginForm("IndexPost", "JobPostings", FormMethod.Post))
                                    {
                                        <input type="hidden" name="FindModel.KeyWords" value="@ViewBag.KeyWords"/>
                                        <input type="hidden" name="FindModel.Location" value="@ViewBag.Location"/>
                                        <input type="hidden" name="FindModel.MaxResults" value="@ViewBag.MaxResults"/>
                                        <input type="hidden" name="FindModel.page" value="@(ViewBag.Page + 1)"/>
                                        <button type="submit" class="btn btn-primary btn-lg right bottom">Next &raquo;</button>
                                    }
                                }
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">

        </div>
    </div>
}
else
{
    <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
        <div class="col-md-2"></div>
        <div class="col-md-4">
            <h4 style="text-align:center;">Sorry nothing was found matching that criteria</h4>
        </div>
        <div class="col-md-4">
            @using (Html.BeginForm("IndexPost", "JobPostings", FormMethod.Post))
            {
                <input type="hidden" name="FindModel.KeyWords" value="@ViewBag.KeyWords"/>
                <input type="hidden" name="FindModel.Location" value="@ViewBag.Location"/>
                <input type="hidden" name="FindModel.MaxResults" value="@ViewBag.MaxResults"/>
                <input type="hidden" name="FindModel.page" value="1"/>
                <button type="submit" class="btn btn-primary btn-lg">Back To Search</button>
            }
        </div>
        <div class="col-md-2"></div>

    </div>
}



</div>


</div>
</section>


<section class="py-5 bg-image overlay-primary fixed overlay" style="background-image: url(@Model.ImageName);">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h2 class="text-white">Looking For A Job?</h2>
                <p class="mb-0 text-white lead">
                    Sign Up Now and save your self some time
                </p>
            </div>
            <div class="col-md-3 ml-auto">
                <a href="/Identity/Account/RegisterJobSeeker" class="btn btn-warning btn-block btn-lg">Sign Up</a>
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script>
        $('[data-toggle="tooltip"]').tooltip();
        var antiForgeryToken = $("input[name='__RequestVerificationToken']").val();

        $('.ViewSummary').click(function () {
            var id = $(this).data('id');
            if ($(".Summary_" + id).is(":hidden")) {
                $(".Summary_" + id).show();
            } else {
                $(".Summary_" + id).hide();
            }
        });

        $('.AddToApplies').click(function () {
            var d = $(this).data('id');
            console.log(d)
            $.ajax({
                method: "POST",
                contentType: 'application/json',
                headers: { "RequestVerificationToken": antiForgeryToken },
                url: "/api/AppliesAPI/addToUserApplies/" + parseInt(d),
                success: function (data) {
                    alertify.success("Added to Applies");
                },
                error: function (xhr) {
                    alertify.error("Could Not Add this Job to your Applies");
                }
            })
        });
    </script>

}